name: HMCCosmetics
main: io.github.fisher2911.hmccosmetics.HMCCosmetics
version: 1.0.0
api-version: 1.17
permissions:
  hmccosmetics.cmd.default:
    default: op
    description: Permission to execute the default command
  hmccosmetics.cmd.dye:
    default: op
    description: Permission to dye armor
  hmccosmetics.cmd.reload:
    default: op
    description: Permission to use the reload command