name: Feature Request
description: Create a feature request to help us keep track of all features you want to be added
labels: [enhancement]
assignees: ["LoJoSho"]
body:
- type: markdown
  attributes:
    value: |
      Please check that the feature you are requesting does not already exist *and/or* hasn't already been requested by someone else.
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of what the problem is, or what feature you want to be implemented.
      placeholder: A good addition would be...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Implementation Description
      description: A clear and concise description of what you want to happen, and any optional **configuration changes** that need to be made.
    validations:
      required: false
