name: Bug Report
description: Create a bug report to help us keep track of all bugs that have to be fixed
title: "[BUG] <title>"
labels: [bug]

body:
  - type: checkboxes
    id: i-have-checked
    attributes:
      label: I have checked...
      options:
        - label: "I am using the latest version of HMCCosmetics"
          required: true
        - label: "I am using the latest version of any dependencies"
          required: true
        - label: "I have checked if any similar bug reports exist"
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A full description of the bug
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Explain how to reproduce this issue step-by-step, in as much detail as possible.
    validations:
      required: true
  - type: textarea
    id: hmcc-version
    attributes:
      label: Plugin Version
      description: Run `version HMCCosmetics` in your console and paste the output
    validations:
      required: true
  - type: textarea
    id: meg-version
    attributes:
      label: ModelEngine Version
      description: "Run `version ModelEngine` in your console and paste the output. Optional if not using balloons."
    validations:
      required: false
  - type: textarea
    id: server-version
    attributes:
      label: Server Version
      description: "Run `version` in your console and paste the output."
    validations:
      required: true
