name: Bug Report
description: Report an issue with HMCCosmetics
labels: [bug]
assignees: ["LoJoSho"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filing an bug report! If you are here to ask a question, use our [Discord server](https://discord.gg/pcm8kWrdNt) instead!
  - type: input
    id: release_version
    attributes:
      label: Plugin Version
      placeholder: vx.x.x
      description: |
        Insert the version of HMCCosmetics you are using (e.g. `v2.2.8`). Before continuing make sure you have the latest version of HMCCosmetics as
        your issue may have already been resolved.
      validations:
        required: true
  - type: input
    id: server_version
    attributes:
      label: Server Version
      placeholder: fork-x-x.x.x
      description: |
        Insert the version of your minecraft server in the format `fork-build-version` (e.g. `PAPER-521-1.19.4`, `PURPUR-1838-1.19.2`)
      validations:
        required: true
  - type: textarea
    id: description
    attributes:
      label: Issue description
      description: Describe the issue in as much detail as possible (Include any error logs in a code block below)
      validations:
        required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Explain how to reproduce this issue step-by-step, in as much detail as possible.
      placeholder: |
        Steps to reproduce:
        1. Do thing
        2. Observe behavior
        3. Post any error logs below
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Issue priority
      description: Please be realistic. If you need to elaborate on your reasoning, please use the issue description field above.
      options:
        - Low (slightly annoying)
        - Medium (should be fixed somewhat soon)
        - High (immediate attention needed)
    validations:
      required: true
  - type: textarea
    id: versions
    attributes:
      label: Other Versions
      placeholder: |
        - ModelEngine R3.0.1 (`\version`)
        - Any other relevant version information such as depenedencies
      description: |
        List any necessary or relevant versions here.
      validations:
        required: false
