blank_issues_enabled: false
contact_links:
    - name: General Questions and Help
      url: https://discord.gg/pcm8kWrdNt
      about: This issue tracker is not for support questions. Please refer to the Hibiscus community's help and discussion discord server.
