name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        java: [ '16', '17' ]
    name: Java ${{ matrix.Java }} on ${{ matrix.os }} sample
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3.6
        with:
          distribution: '<distribution>'
          java-version: ${{ matrix.java }}
          cache: 'gradle'
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build